Repository J-millar99/SK_Rookies_Mini_Project2, pull requests merged in 2025-06, with the labels that each got.

#45 [feature#22] token 인증 처리
  backend/build.gradle
  backend/src/main/java/com/miniproject/rookiejangter/controller/UserController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/UserDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/User.java
  backend/src/main/java/com/miniproject/rookiejangter/provider/JwtProvider.java
  backend/src/main/java/com/miniproject/rookiejangter/service/UserService.java
  backend/src/main/resources/application-test.yml
  backend/src/test/java/com/miniproject/rookiejangter/service/UserServiceTest.java
  logs/spring.log
Labels: feature

#44 Fetch#43: 리팩토링 및 UI개선
  frontend/src/components/KeywordSearch.jsx
  frontend/src/components/PriceToggleButton.jsx
  frontend/src/components/ProductActions.jsx
  frontend/src/components/ProductCard.jsx
  frontend/src/components/ProductImageSlider.jsx
  frontend/src/components/ProductSearch.jsx
  frontend/src/components/ProductsList.jsx
  frontend/src/pages/ProductDetailPage.jsx
  frontend/src/pages/ProductsPage.jsx
Labels: refactor

#52 Feature/#48 docker를 사용하여 front를 npm으로 실행
  backend/src/main/java/com/miniproject/rookiejangter/config/SecurityConfig.java
  backend/src/main/java/com/miniproject/rookiejangter/config/WebConfig.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/AuthController.java
  backend/src/main/resources/static/index.html
  frontend/Dockerfile
  frontend/docker-compose.yml
  frontend/src/api/auth.js
  frontend/src/components/LoginForm.jsx
  frontend/vite.config.js
  logs/spring.log
Labels: feature

#60 docker-compose 추가
  docker-compose.yml
  frontend/Dockerfile
Labels: enhancement

#61 enhancement/#59 경로 수정
  docker-compose.yml
Labels: enhancement

#69 feature/#62 : Product Controller
  backend/src/main/java/com/miniproject/rookiejangter/controller/AdminController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/AuthController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/UserController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ProductDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/service/ProductService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/UserService.java
  logs/spring.log
Labels: feature

#68 feature/#66 DibsController 코드 구현 및 Service, Repository, DTO 코드 수정
  backend/src/main/java/com/miniproject/rookiejangter/controller/DibsController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/DibsDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Product.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/DibsRepository.java
  backend/src/main/java/com/miniproject/rookiejangter/service/DibsService.java
Labels: feature

#78 feature#75 관리자 페이지 Contoller 추가
  backend/.gitignore
  backend/src/main/java/com/miniproject/rookiejangter/controller/AdminController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/AuthController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/DibsController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/UserDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/provider/JwtAuthenticationFilter.java
  backend/src/main/java/com/miniproject/rookiejangter/provider/JwtProvider.java
  backend/src/main/java/com/miniproject/rookiejangter/service/AuthService.java
  frontend/.gitignore
Labels: feature

#80 fetch#79: 회원 조회/수정/삭제 API 적용
  frontend/src/pages/MyPage.jsx
Labels: feature

#89 feature#87 예약과 알림 조회
  backend/src/main/java/com/miniproject/rookiejangter/controller/ChatController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/ProductController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/UserController.java
  backend/src/main/java/com/miniproject/rookiejangter/service/NotificationService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/ReservationService.java
Labels: feature

#92 Fetch#91: 관리자페이지 추가 및 회원목록/상세정보/밴 기능 추가
  frontend/src/App.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/LoginForm.jsx
  frontend/src/pages/AdminUserPage.jsx
Labels: feature

#97 feat#96: 거래 예약 -> 판매자 알림 백엔드 구현
  backend/src/main/java/com/miniproject/rookiejangter/config/WebConfig.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/AdminController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/ImageController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/NotificationController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/ReportController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/ReservationController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/TradeController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/UserController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/WholeProductController.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/BanDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ProductDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ReservationDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ReviewDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/NotificationRepository.java
  backend/src/main/java/com/miniproject/rookiejangter/service/NotificationService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/ReservationService.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/service/NotificationServiceTest.java
  backend/src/test/java/com/miniproject/rookiejangter/service/ReservationServiceTest.java
  frontend/Dockerfile
  frontend/src/App.jsx
  frontend/src/api/axios.js
  frontend/src/api/notificationService.js
  frontend/src/components/Header.jsx
  frontend/src/components/LoginForm.jsx
  frontend/src/components/NotificationList.jsx
  frontend/src/features/auth/authSlice.js
  frontend/src/features/auth/authThunks.js
  frontend/src/index.js
  frontend/src/main.jsx
  frontend/src/pages/MyProductDetailPage.jsx
  frontend/src/pages/ProductRegisterPage.jsx
  frontend/src/pages/ProductsPage.jsx
  frontend/vite.config.js
Labels: feature

#99 fetch#98: ReactComponents&Props 설계서 작성
  docs/ReactComponents&Props.md
  frontend/src/App.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/LoginForm.jsx
  frontend/src/components/PhoneAuthForm.jsx
  frontend/src/pages/MyPage.jsx
  frontend/src/pages/RegisterPage.jsx
Labels: docs

#108 fetch#107: 0608 10시 기준 frontend components & Props 설계서
  docs/ReactComponents&Props.md
Labels: docs

#110 Fetch#109: 구현 기능 수정
  frontend/src.zip
  frontend/src/components/AreaSelectModal.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/ProductSearch.jsx
  frontend/src/components/ReportModal.jsx
  frontend/src/pages/AdminUserPage.jsx
  frontend/src/pages/MyPage.jsx
  frontend/src/pages/ProductDetailPage.jsx
Labels: bugfix, enhancement

#113 Refactor#112: 문서 수정, 백엔드 코드 주석 수정
  README.md
  backend/src/main/java/com/miniproject/rookiejangter/entity/Cancelation.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/CancelationReason.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Product.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Report.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/ReportReason.java
  docs/domain.md
  docs/entity.md
Labels: docs, refactor
