Repository J-millar99/SK_Rookies_Mini_Project2, pull requests merged in 2025-05, with the labels that each got.

#5 Fetch#4: 회원가입 페이지
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/api/auth.js
  frontend/src/assets/react.svg
  frontend/src/components/PhoneAuthForm.jsx
  frontend/src/components/SignUpForm.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/RegisterPage.jsx
  frontend/vite.config.js
Labels: feature

#11 docs/#3: entity.md 생성
  docs/entity.md
Labels: docs

#12 docs/#3: entity update
  docs/entity.md
Labels: docs

#23 docs/#1 RESTAPI update
  docs/RESTAPI.md
Labels: docs

#27 Feature#24: DTO 코드 추가
  backend/logs/spring.log
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/AreaDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/BanDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/BumpDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/CancelationDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/CancelationReasonDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/CategoryDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ChatDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/CompleteDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/DibsDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ImageDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/MessageDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/NotificationDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/PostDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ReportDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ReportReasonDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ReservationDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ReviewDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/UserDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Ban.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Cancelation.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Goods.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Message.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Post.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Reservation.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Review.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/User.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/GoodsRepository.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/MessageRepository.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/BanRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ChatRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/CompleteRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/DibsRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/GoodsRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/MessageRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/PostRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ReportRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/UserRepositoryTest.java
Labels: docs, feature

#30 Fetch#29:UI/UX 추가
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/about.txt
  frontend/public/android-chrome-192x192.png
  frontend/public/android-chrome-512x512.png
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon.ico
  frontend/public/site.webmanifest
  frontend/src/App.jsx
  frontend/src/api/auth.js
  frontend/src/components/Footer.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/Layout.jsx
  frontend/src/components/LoginForm.jsx
  frontend/src/components/ProductCard.jsx
  frontend/src/main.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/MyPage.jsx
  frontend/src/pages/SignupPage.jsx
  frontend/vite.config.js
Labels: feature

#32 refactor#31: RepositoryTest 일부 개선, 문서 일부 최신화
  backend/logs/spring.log
  backend/src/test/java/com/miniproject/rookiejangter/repository/BumpRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/CancelationRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ChatRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/CompleteRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/DibsRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ImageRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/MessageRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/NotificationRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/PostRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ReviewRepositoryTest.java
  docs/RESTAPI.md
  docs/domain.md
  docs/entity.md
Labels: refactor

#37 Refactor#36: 엔티티명 변경: Post -> Product, 문서 최신화
  backend/logs/spring.log
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/BumpDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ChatDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/CompleteDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/DibsDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ProductDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ReservationDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Bump.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Category.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Chat.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Complete.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Dibs.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Image.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Product.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/Reservation.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/User.java
  backend/src/main/java/com/miniproject/rookiejangter/exception/BusinessException.java
  backend/src/main/java/com/miniproject/rookiejangter/exception/ErrorCode.java
  backend/src/main/java/com/miniproject/rookiejangter/exception/advice/DefaultExceptionAdvice.java
  backend/src/main/java/com/miniproject/rookiejangter/exception/advice/ErrorObject.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/BumpRepository.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/ChatRepository.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/CompleteRepository.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/DibsRepository.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/ImageRepository.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/PostRepository.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/ProductRepository.java
  backend/src/main/java/com/miniproject/rookiejangter/repository/ReservationRepository.java
  backend/src/main/java/com/miniproject/rookiejangter/service/AreaService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/BumpService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/CategoryService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/CompleteService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/DibsService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/ImageService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/ProductService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/ReservationService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/UserService.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/BumpRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ChatRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/CompleteRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/DibsRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ImageRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ProductRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ReportRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ReservationRepositoryTest.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ReviewRepositoryTest.java
  docs/RESTAPI.md
  docs/domain.md
  docs/entity.md
Labels: docs, refactor

#35 feat#33: 예외 정의, Service 일부 통합, 문서 최신화
  backend/logs/spring.log
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ChatDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/DibsDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/controller/dto/ReservationDTO.java
  backend/src/main/java/com/miniproject/rookiejangter/entity/User.java
  backend/src/main/java/com/miniproject/rookiejangter/exception/BusinessException.java
  backend/src/main/java/com/miniproject/rookiejangter/exception/ErrorCode.java
  backend/src/main/java/com/miniproject/rookiejangter/exception/advice/DefaultExceptionAdvice.java
  backend/src/main/java/com/miniproject/rookiejangter/exception/advice/ErrorObject.java
  backend/src/main/java/com/miniproject/rookiejangter/service/AreaService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/BumpService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/CategoryService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/CompleteService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/DibsService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/ImageService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/PostService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/ReservationService.java
  backend/src/main/java/com/miniproject/rookiejangter/service/UserService.java
  backend/src/test/java/com/miniproject/rookiejangter/repository/ReviewRepositoryTest.java
  docs/entity.md
Labels: feature
